# Generated by Django 2.2.10 on 2020-06-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinstance',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Approved'), ('p', 'Pending'), ('r', 'Rejected'), ('c', 'Sync complete'), ('f', 'Sync fail')], default='p', help_text='Leave Request Status', max_length=1),
        ),
    ]
