# Generated by Django 3.0.7 on 2020-06-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20200604_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeinstance',
            options={'ordering': ['-created_date']},
        ),
    ]
