# Generated by Django 3.0.7 on 2020-06-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20200607_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Approved'), ('p', 'Pending'), ('r', 'Rejected'), ('d', 'Deleted'), ('c', 'Sync complete'), ('f', 'Sync fail')], default='p', help_text='Leave Request Status', max_length=1),
        ),
    ]
