# Generated by Django 3.0.7 on 2020-06-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_employeeinstance_leave_resaon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinstance',
            name='leave_resaon',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
