# Generated by Django 3.0.7 on 2021-04-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_auto_20200708_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinstance',
            name='document_data',
            field=models.BinaryField(null=True),
        ),
    ]
