# Generated by Django 3.0.12 on 2021-04-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_employeeinstance_document_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinstance',
            name='emp_type',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
