# Generated by Django 3.0.12 on 2021-06-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0011_employeeinstance_emp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinstance',
            name='leave_no',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeeinstance',
            name='op1',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employeeinstance',
            name='op2',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employeeinstance',
            name='opn1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='employeeinstance',
            name='opn2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
