# Generated by Django 2.2.10 on 2020-02-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TclDailyWorking',
            fields=[
                ('cnt_id', models.DecimalField(decimal_places=0, max_digits=13, primary_key=True, serialize=False)),
                ('cus_name_th', models.CharField(blank=True, max_length=120, null=True)),
                ('emp_id', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('fname', models.CharField(blank=True, db_column='Fname', max_length=71, null=True)),
                ('shf_type', models.CharField(blank=True, max_length=1, null=True)),
                ('shf_desc', models.CharField(blank=True, max_length=30, null=True)),
                ('dly_date', models.CharField(blank=True, max_length=30, null=True)),
                ('upd_date', models.CharField(blank=True, db_column='UPD_Date', max_length=30, null=True)),
            ],
            options={
                'db_table': 'TCL_Daily_Working',
                'managed': False,
            },
        ),
    ]
