# Generated by Django 3.0.12 on 2021-04-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeM1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_access_employee_m1', 'Able to access M1 employee application.'), ('can_access_employee_m1_pay_slip', 'Able to access M1 employee pay slip.')),
            },
        ),
    ]
