# Generated by Django 2.2.10 on 2020-03-01 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComZone',
            fields=[
                ('zone_id', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('zone_th', models.CharField(blank=True, max_length=30, null=True)),
                ('zone_en', models.CharField(blank=True, max_length=30, null=True)),
                ('zone_emp_id', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('upd_date', models.DateTimeField(blank=True, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=10, null=True)),
                ('upd_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'COM_ZONE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContractPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.ForeignKey(db_column='username', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique=True)),
                ('zone', models.ForeignKey(blank=True, db_column='zone_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='system.ComZone')),
            ],
            options={
                'db_table': 'contract_policy',
            },
        ),
    ]
