# Generated by Django 2.2.10 on 2020-03-01 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20200301_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractpolicy',
            options={'verbose_name': 'Contract Policy', 'verbose_name_plural': 'Contract Policy'},
        ),
    ]
