# Generated by Django 3.0.12 on 2021-04-28 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20200301_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlookEmailActiveUserList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=datetime.date.today, null=True)),
                ('created_by', models.CharField(blank=True, default='System', max_length=50, null=True)),
            ],
            options={
                'db_table': 'system_outlook_email_active_user_list',
                'managed': True,
                'unique_together': {('email',)},
            },
        ),
    ]
