# Generated by Django 3.0.12 on 2021-05-01 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_outlookemailactiveuserlist_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlookemailactiveuserlist',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
