# Generated by Django 3.0.7 on 2021-04-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrpoActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atid', models.IntegerField(db_column='atID')),
                ('atname', models.CharField(db_column='atName', max_length=20)),
            ],
            options={
                'db_table': 'PRPO_Actions',
                'managed': False,
            },
        ),
    ]
