# Generated by Django 3.0.7 on 2021-04-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prpo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrpoCompany',
            fields=[
                ('cpid', models.IntegerField(db_column='cpID', primary_key=True, serialize=False)),
                ('cpnumber', models.CharField(db_column='cpNumber', max_length=5)),
                ('cpcountry', models.IntegerField(db_column='cpCountry')),
                ('cpname', models.CharField(db_column='cpName', max_length=50)),
                ('cpshortcut', models.CharField(db_column='cpShortCut', max_length=2)),
                ('cpaltername', models.CharField(db_column='cpAlterName', max_length=100)),
                ('cpaddress', models.CharField(blank=True, db_column='cpAddress', max_length=150, null=True)),
                ('cpalteraddr', models.CharField(blank=True, db_column='cpAlterAddr', max_length=150, null=True)),
                ('cptel', models.CharField(blank=True, db_column='cpTel', max_length=30, null=True)),
                ('cpfax', models.CharField(blank=True, db_column='cpFax', max_length=30, null=True)),
                ('cpcurrency', models.IntegerField(db_column='cpCurrency')),
                ('cplogo', models.CharField(blank=True, db_column='cpLogo', max_length=100, null=True)),
                ('cpponotes', models.TextField(blank=True, db_column='cpPONotes', null=True)),
                ('cpvpflag', models.BooleanField(db_column='cpVPFlag')),
                ('cpverifypercent', models.FloatField(db_column='cpVerifyPercent')),
                ('cpvvflag', models.BooleanField(db_column='cpVVFlag')),
                ('cpverifyvalue', models.FloatField(db_column='cpVerifyValue')),
                ('cpverifyapprover', models.BooleanField(db_column='cpVerifyApprover')),
                ('cpprmaxid', models.IntegerField(db_column='cpPRMaxID')),
                ('cppomaxid', models.IntegerField(db_column='cpPOMaxID')),
                ('fldremainnum', models.DecimalField(blank=True, db_column='FldRemainNum', decimal_places=3, max_digits=18, null=True)),
                ('fldremainchar1', models.CharField(blank=True, db_column='FldRemainChar1', max_length=30, null=True)),
                ('fldremainchar2', models.CharField(blank=True, db_column='FldRemainChar2', max_length=30, null=True)),
                ('opuser', models.IntegerField(db_column='opUser')),
                ('optime', models.DateTimeField(db_column='opTime')),
            ],
            options={
                'db_table': 'PRPO_Company',
                'managed': False,
            },
        ),
    ]
