# Generated by Django 3.0.7 on 2020-06-25 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20200625_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_creator',
            new_name='updated_by',
        ),
    ]
