# Generated by Django 3.0.12 on 2021-06-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_comdivision'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidEmployeeVaccineUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('upd_date', models.DateTimeField(blank=True, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=10, null=True)),
                ('upd_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'covid_employee_vaccine_update',
                'managed': True,
            },
        ),
    ]
