# Generated by Django 3.0.12 on 2021-06-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_covidemployeevaccineupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidemployeevaccineupdate',
            name='file_attach_data',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='covidemployeevaccineupdate',
            name='file_attch',
            field=models.FileField(null=True, upload_to='documents/covid/'),
        ),
        migrations.AddField(
            model_name='covidemployeevaccineupdate',
            name='get_vaccine_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='covidemployeevaccineupdate',
            name='get_vaccine_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
