# Generated by Django 3.0.12 on 2021-06-11 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20210611_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covidemployeevaccineupdate',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
