# Generated by Django 3.0.12 on 2021-06-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20210611_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidemployeevaccineupdate',
            name='get_vaccine_count',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True),
        ),
    ]
