# Generated by Django 3.0.12 on 2021-06-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_covidemployeevaccineupdate_get_vaccine_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CovidEmployeeVaccineUpdate',
        ),
    ]
