# Generated by Django 3.0.12 on 2021-06-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_covidemployeevaccineupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidemployeevaccineupdate',
            name='op1',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='covidemployeevaccineupdate',
            name='op2',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='covidemployeevaccineupdate',
            name='opd1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='covidemployeevaccineupdate',
            name='opd2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='covidemployeevaccineupdate',
            name='opn1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='covidemployeevaccineupdate',
            name='opn2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
