# Generated by Django 3.0.12 on 2021-06-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_auto_20210611_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidemployeevaccineupdate',
            name='phone_number',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
