# Generated by Django 3.0.12 on 2021-06-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_covidemployeevaccineupdate_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covidemployeevaccineupdate',
            old_name='get_vaccine_count',
            new_name='get_vaccine_status',
        ),
    ]
