# Generated by Django 3.0.12 on 2021-06-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_auto_20210611_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidemployeevaccineupdate',
            name='file_attach_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
