# Generated by Django 3.0.12 on 2021-06-11 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_covidemployeevaccineupdate_file_attach_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CovidEmployeeVaccineUpdate',
        ),
    ]
