# Generated by Django 3.0.12 on 2021-06-11 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_covidemployeevaccineupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covidemployeevaccineupdate',
            old_name='file_attch',
            new_name='file_attach',
        ),
    ]
