# Generated by Django 3.0.12 on 2021-06-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_auto_20210611_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidemployeevaccineupdate',
            name='op3',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='covidemployeevaccineupdate',
            name='op4',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='covidemployeevaccineupdate',
            name='op5',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
