# Generated by Django 3.0.12 on 2021-06-16 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0019_auto_20210615_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPasswordLog',
            fields=[
                ('emp_id', models.DecimalField(decimal_places=0, max_digits=7, primary_key=True, serialize=False)),
                ('is_password_changed', models.BooleanField(default=False)),
                ('is_password_expired', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
                ('created_by', models.CharField(blank=True, default='system', max_length=10, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=10, null=True)),
                ('upd_flag', models.CharField(blank=True, default='A', max_length=1, null=True)),
            ],
            options={
                'db_table': 'auth_user_password_log',
                'managed': True,
            },
        ),
    ]
