# Generated by Django 3.0.12 on 2021-06-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0020_userpasswordlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpasswordlog',
            name='is_password_changed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userpasswordlog',
            name='is_password_expired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
