# Generated by Django 3.0.12 on 2021-06-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0022_userloginlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginlog',
            name='device',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
