# Generated by Django 3.0.12 on 2021-04-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EPayslipM1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'sp_slip1',
                'permissions': (('can_access_e_payslip_m1', 'Able to access E-Payslip M1.'),),
                'managed': False,
            },
        ),
    ]
