# Generated by Django 3.0.7 on 2021-04-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleavereport', '0002_auto_20210303_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eleavereports',
            options={'permissions': (('can_view_m1_report', 'Can view M1 report'), ('can_view_m1_approved_leave_request_report', 'Can view M1 approved leave request report'))},
        ),
    ]
