# Generated by Django 3.0.7 on 2021-04-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleavereport', '0003_auto_20210415_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eleavereports',
            options={'permissions': (('can_view_m1_report', 'Can view M1 report'), ('can_view_m1_leave_report', 'Can view M1 leave report'))},
        ),
    ]
