# Generated by Django 3.0.12 on 2021-04-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleavereport', '0004_auto_20210415_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eleavereports',
            options={'permissions': (('can_view_m1_report', 'Can view M1 report'), ('can_view_m1_leave_report', 'Can view M1 leave report'), ('can_view_m5_report', 'Can view M5 report'), ('can_view_m5_leave_report', 'Can view M5 leave report'))},
        ),
    ]
