# Generated by Django 3.0.12 on 2021-04-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleavereport', '0005_auto_20210429_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eleavereports',
            options={'permissions': (('can_view_m1_report', 'Can view M1 reports'), ('can_view_m1_leave_report', 'Can view M1 leave report'), ('can_view_m3_report', 'Can view M3 reports'), ('can_view_m3_leave_report', 'Can view M3 leave report'), ('can_view_m5_report', 'Can view M5 reports'), ('can_view_m5_leave_report', 'Can view M5 leave report'))},
        ),
    ]
