# Generated by Django 3.0.7 on 2021-04-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ITcontractDB_M',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('dept', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('description1', models.CharField(blank=True, max_length=100, null=True)),
                ('person', models.CharField(blank=True, max_length=100, null=True)),
                ('tel', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, db_column='price', decimal_places=2, max_digits=15, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('ae_mail', models.CharField(blank=True, max_length=100, null=True)),
                ('ae_mail1', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('upd_date', models.DateTimeField()),
                ('upd_by', models.CharField(blank=True, max_length=50, null=True)),
                ('upd_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('opd1', models.DateTimeField()),
                ('opd2', models.DateTimeField()),
                ('op1', models.CharField(blank=True, max_length=100, null=True)),
                ('op2', models.CharField(blank=True, max_length=100, null=True)),
                ('op3', models.CharField(blank=True, max_length=200, null=True)),
                ('opn1', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('opn2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('opn3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('afile', models.BinaryField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'ITcontractDB',
                'ordering': ('id',),
                'managed': False,
            },
        ),
    ]
