# Generated by Django 3.0.7 on 2021-04-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITcontract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itcontractdb',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itcontractdb',
            name='vendor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
