# Generated by Django 3.0.7 on 2021-04-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITcontract', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itcontractdb_m',
            options={'managed': True, 'ordering': ('id',)},
        ),
    ]
