# Generated by Django 3.0.7 on 2021-04-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITcontract', '0002_auto_20210407_1358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ITcontractDB_M',
            new_name='ITcontractDB',
        ),
    ]
