# Generated by Django 3.0.7 on 2021-04-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITcontract', '0002_auto_20210415_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='itcontractdb',
            name='ae_mail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itcontractdb',
            name='ae_mail1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itcontractdb',
            name='description1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itcontractdb',
            name='e_mail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itcontractdb',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='itcontractdb',
            name='op1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itcontractdb',
            name='op2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itcontractdb',
            name='op3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='itcontractdb',
            name='opd1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='itcontractdb',
            name='opd2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='itcontractdb',
            name='opn1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='itcontractdb',
            name='opn2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='itcontractdb',
            name='opn3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='itcontractdb',
            name='person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itcontractdb',
            name='price',
            field=models.DecimalField(blank=True, db_column='price', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='itcontractdb',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itcontractdb',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='itcontractdb',
            name='tel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itcontractdb',
            name='upd_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itcontractdb',
            name='upd_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='itcontractdb',
            name='upd_flag',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
