# Generated by Django 3.0.7 on 2021-04-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITcontract', '0003_auto_20210407_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itcontractdb',
            name='id',
            field=models.AutoField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
