# Generated by Django 3.0.7 on 2021-04-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITcontract', '0003_auto_20210415_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='itcontractdb',
            name='afile',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='itcontractdb',
            name='afile_data',
            field=models.BinaryField(null=True),
        ),
    ]
