# Generated by Django 3.0.7 on 2021-04-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITcontract', '0004_auto_20210408_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itcontractdb',
            options={'managed': False, 'ordering': ('id',)},
        ),
    ]
