# Generated by Django 3.0.12 on 2021-04-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITcontract', '0005_itcontractalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='itcontractalert',
            name='minimum_day',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
