# Generated by Django 3.0.7 on 2021-04-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITcontract', '0005_auto_20210408_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itcontractdb',
            options={'managed': True, 'ordering': ('id',)},
        ),
    ]
