# Generated by Django 3.0.12 on 2021-04-21 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITcontract', '0006_itcontractalert_minimum_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ITContractAlert',
        ),
    ]
