# Generated by Django 3.0.7 on 2021-04-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITcontract', '0006_auto_20210408_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itcontractdb',
            name='id',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
