# Generated by Django 3.0.12 on 2021-04-21 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITcontract', '0010_schedulealertsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulealertsetting',
            old_name='active',
            new_name='alert_active',
        ),
        migrations.RenameField(
            model_name='schedulealertsetting',
            old_name='alert_description',
            new_name='app_name',
        ),
        migrations.RenameField(
            model_name='schedulealertsetting',
            old_name='alert_email',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='schedulealertsetting',
            old_name='minimum_day',
            new_name='reach_minimum_day',
        ),
        migrations.RenameField(
            model_name='schedulealertsetting',
            old_name='alert_name',
            new_name='send_email_to',
        ),
    ]
