# Generated by Django 3.0.12 on 2021-04-21 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITcontract', '0011_auto_20210421_0128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduleAlertSetting',
        ),
    ]
