# Generated by Django 3.0.12 on 2021-04-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITcontract', '0013_schedulealertsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulealertsetting',
            old_name='send_email_to',
            new_name='send_to_email',
        ),
        migrations.AddField(
            model_name='schedulealertsetting',
            name='send_to_group_mail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
