# Generated by Django 3.0.12 on 2021-04-21 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITcontract', '0014_auto_20210421_0146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduleAlertSetting',
        ),
    ]
