# Generated by Django 3.0.12 on 2021-04-21 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITcontract', '0018_schedulealertsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduleAlertSetting',
        ),
    ]
