# Generated by Django 3.0.12 on 2021-04-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITcontract', '0020_schedulealertsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduleAlertSetting',
        ),
    ]
